### ISSUE TITLE
bai 11

### ISSUE THREAD

**Issue by quangthaiqt** [quangthai-188/learn-laravel#2]
![image](https://github.com/quangthai-188/learn-laravel/assets/126308468/4f9d38cc-2c60-4f5a-9c0a-dd6b3022e653)
![image](https://github.com/quangthai-188/learn-laravel/assets/126308468/81648642-b3c4-4bf1-a5fe-46e2389bf568)
![image](https://github.com/quangthai-188/learn-laravel/assets/126308468/781c53f4-cd88-4c6b-ab19-08883d5d04e8)
![image](https://github.com/quangthai-188/learn-laravel/assets/126308468/3045b262-ef74-4f31-bb81-f61b4952de31)

**Comment by tranquangtanqt** [comment]
Chỉnh sửa _routers\web.php_:
```php
Route::post('postForm',['as'=>'postForm','uses'=> [MyController::class,'postForm']]);
```
Thành:
```php
Route::post('postForm', [MyController::class, 'postForm'])->name('postForm');
```
